=== lucamerighi/esami_tecweb/TW-T-170915-2x/grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- uso facet -->
	
	<!-- enumerazione -->
	
	
	<!-- Restrizione valore numero -->
	<xs:simpleType name="annoType">
	<xs:restriction base="xs:decimal">
		<xs:totalDigits value="4"/>
		<xs:maxInclusive value="2020"/>
		<xs:minInclusive value="1700"/>
	</xs:restriction>
	</xs:simpleType>
	
	<!-- regular expression -->
	<xs:simpleType name="lunghType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9][0-9]:[0-5][0-9]"/>
	</xs:restriction>
	</xs:simpleType>
	
	
	<!--esempi-->
	
	<xs:complexType name="branoType">
	<xs:sequence>
		<xs:element name="titolobrano" type="xs:string"/>
		<xs:element name="lunghezza" type="lunghType" />
	</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="albumType">
	<xs:sequence>
		<xs:element name="titoloalbum" type="xs:string"/>
		<xs:element name="anno" type="annoType"/>
		<xs:element name="brano" type="branoType"  minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	</xs:complexType>


	<xs:complexType name="musicistaType">
	<xs:sequence>
		<xs:element name="nome" type="xs:string"/>
		<xs:element name="cognome" type="xs:string"/>
		<xs:element name="nomeArte" type="xs:string" minOccurs="0"  maxOccurs="1"/>
		<xs:element name="genere" type="xs:string"/>
		<xs:element name="album" type="albumType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>		
	</xs:complexType>
	
	
	
	<xs:complexType name="BibliotecaType">
	<xs:sequence>
		<xs:element name="musicista" type="musicistaType" minOccurs="0" maxOccurs="unbounded" />
	</xs:sequence>
	</xs:complexType>
	
	
	<xs:element name="biblioteca" type="BibliotecaType"/>
		
</xs:schema>

=== lucamerighi/esami_tecweb/TW-T-170915-2x/fileXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grammar.xsd">
	
<musicista>
	<nome>red hot</nome>
	<cognome>chili peppers</cognome>
	<nomeArte>rhcp</nomeArte>
	<genere>rock</genere>
	<album>
		<titoloalbum>californication</titoloalbum>
		<anno>1987</anno>
		<brano>
			<titolobrano>dani california</titolobrano>
			<lunghezza>02:34</lunghezza>
		</brano>
		<brano>
			<titolobrano>scar tissue</titolobrano>
			<lunghezza>03:34</lunghezza>
		</brano>
		
	</album>
	<album>
		<titoloalbum>lovesex</titoloalbum>
		<anno>1989</anno>
		<brano>
			<titolobrano>under the bridge</titolobrano>
			<lunghezza>04:45</lunghezza>
		</brano>
		<brano>
			<titolobrano>snow</titolobrano>
			<lunghezza>01:45</lunghezza>
		</brano>
	</album>
</musicista>	

<musicista>
	<nome>foo</nome>
	<cognome>figthers</cognome>
	<nomeArte>ff</nomeArte>
	<genere>rock</genere>
	<album>
		<titoloalbum>concrete and gold</titoloalbum>
		<anno>2018</anno>
		<brano>
			<titolobrano>learn to fly</titolobrano>
			<lunghezza>04:50</lunghezza>
		</brano>
	</album>
</musicista>	

<musicista>
	<nome>bon</nome>
	<cognome>jovi</cognome>
	<nomeArte>bj</nomeArte>
	<genere>poprock</genere>
	<album>
		<titoloalbum>best of</titoloalbum>
		<anno>2002</anno>
		<brano>
			<titolobrano>livin on a prayer</titolobrano>
			<lunghezza>03:50</lunghezza>
		</brano>
	</album>
</musicista>

	
</biblioteca>
