=== lucamerighi/esami_tecweb/TW-T-160916-2x/grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="colType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Colore"/>
		<xs:enumeration value="BN"/>
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="formatoType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="Blu-Ray"/>
		<xs:enumeration value="DVD"/>
		<xs:enumeration value="Divx"/>
		<xs:enumeration value="VHS"/>
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="dispType">
	<xs:restriction base="xs:string">
		<xs:enumeration value="si"/>
		<xs:enumeration value="no"/>
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="pellType">
	<xs:restriction base="xs:decimal">
		<xs:enumeration value="32"/>
		<xs:enumeration value="16"/>
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="annoType">
	<xs:restriction base="xs:decimal">
		<xs:totalDigits value="4"/>
		<xs:maxInclusive value="2020"/>
		<xs:minInclusive value="1700"/>
	</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="collocType">
	<xs:restriction base="xs:string">
		<xs:pattern value="[0-9][0-9]\.[0-9][0-9]\.[0-9][0-9]\.[0-9][0-9][0-9]\.[A-Z][A-Z][A-Z]"/>
	</xs:restriction>
	</xs:simpleType>
	
	
	<xs:complexType  name="audiovType">
		<xs:sequence>
			<xs:element name="cognomeReg" type="xs:string" />
			<xs:element name="nomeReg" type="xs:string"/>
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="nazione" type="xs:string" />
			<xs:element name="lingua" type="xs:string"/>
			<xs:element name="colore" type="colType" />
			<xs:element name="durata" type="xs:decimal" />
			<xs:element name="tipologia" type="xs:string"/>
			<xs:element name="formato" type="formatoType"/>
			<xs:element name="anno" type="annoType" />
			<xs:element name="disponibilita" type="dispType"/>
			<xs:element name="collocazione" type="collocType"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType  name="pellicolaType">
		<xs:sequence>
			<xs:element name="regia" type="xs:string" />
			<xs:element name="titolo" type="xs:string"/>
			<xs:element name="statoConserv" type="xs:string" />
			<xs:element name="tipoPell" type="pellType"/>
			
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="cineteca">
		<xs:complexType>
			<xs:choice  maxOccurs="unbounded">
				<xs:element name="audiovisivo" type="audiovType" />
				<xs:element name="pellicola" type="pellicolaType" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
		
</xs:schema>

=== lucamerighi/esami_tecweb/TW-T-160916-2x/fileXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<cineteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grammar.xsd">
	
	<pellicola>
		<regia>ABS</regia>
		<titolo>Giallo</titolo>
		<statoConserv>buono</statoConserv>
		<tipoPell>32</tipoPell>
	</pellicola>
	
	<pellicola>
		<regia>FNSKID</regia>
		<titolo>Blu</titolo>
		<statoConserv>cattivo</statoConserv>
		<tipoPell>16</tipoPell>
	</pellicola>
	
	
	<pellicola>
		<regia>DKLDIO</regia>
		<titolo>Rosso</titolo>
		<statoConserv>cattivo</statoConserv>
		<tipoPell>16</tipoPell>
	</pellicola>
	
	
	<pellicola>
		<regia>DKDJPPS</regia>
		<titolo>Verde</titolo>
		<statoConserv>buono</statoConserv>
		<tipoPell>16</tipoPell>
	</pellicola>
	
	<audiovisivo>
		<cognomeReg>Rossi</cognomeReg>
		<nomeReg>Mario</nomeReg>
		<titolo>roma</titolo>
		<nazione>it</nazione>
		<lingua>ita</lingua>
		<colore>BN</colore>
		<durata>124</durata>
		<tipologia>Docum</tipologia>
		<formato>DVD</formato>
		<anno>1937</anno>
		<disponibilita>si</disponibilita>
		<collocazione>12.45.78.325.DNH</collocazione>	
	</audiovisivo>
	
	<audiovisivo>
		<cognomeReg>Verdi</cognomeReg>
		<nomeReg>Luisa</nomeReg>
		<titolo>Bologna</titolo>
		<nazione>it</nazione>
		<lingua>ita</lingua>
		<colore>Colore</colore>
		<durata>234</durata>
		<tipologia>Film</tipologia>
		<formato>DVD</formato>
		<anno>2001</anno>
		<disponibilita>no</disponibilita>
		<collocazione>12.45.78.325.DNH</collocazione>	
	</audiovisivo>
	
	<audiovisivo>
		<cognomeReg>Gialli</cognomeReg>
		<nomeReg>Lina</nomeReg>
		<titolo>Venezia</titolo>
		<nazione>it</nazione>
		<lingua>ita</lingua>
		<colore>BN</colore>
		<durata>124</durata>
		<tipologia>Doc</tipologia>
		<formato>DVD</formato>
		<anno>1987</anno>
		<disponibilita>si</disponibilita>
		<collocazione>12.45.78.325.DNH</collocazione>	
	</audiovisivo>
	
	<audiovisivo>
		<cognomeReg>Tomms</cognomeReg>
		<nomeReg>Tom</nomeReg>
		<titolo>Milano</titolo>
		<nazione>it</nazione>
		<lingua>ita</lingua>
		<colore>Colore</colore>
		<durata>45</durata>
		<tipologia>Dos</tipologia>
		<formato>DVD</formato>
		<anno>1843</anno>
		<disponibilita>si</disponibilita>
		<collocazione>12.45.78.325.DNH</collocazione>	
	</audiovisivo>
	
	<audiovisivo>
		<cognomeReg>Pippo</cognomeReg>
		<nomeReg>Filo</nomeReg>
		<titolo>Firenze</titolo>
		<nazione>id</nazione>
		<lingua>ida</lingua>
		<colore>BN</colore>
		<durata>65</durata>
		<tipologia>fsdd</tipologia>
		<formato>DVD</formato>
		<anno>1978</anno>
		<disponibilita>no</disponibilita>
		<collocazione>12.45.78.325.DNH</collocazione>	
	</audiovisivo>
	
</cineteca>
